# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Find solution file
      run: |
        SOLUTION_FILE=$(ls *.sln | head -n 1)
        echo "SOLUTION_FILE=$SOLUTION_FILE" >> "$GITHUB_ENV"
      shell: bash
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore
    - name: Test
      run: dotnet test ${{ env.SOLUTION_FILE }} --no-build --verbosity normal --blame-hang-timeout 60s --blame-hang-dump-type mini
